server:
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      kubernetes.io/tls-acme: "true"
      nginx.ingress.kubernetes.io/ssl-passthrough: "true"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    hosts:
      - argocd.laurencechau.com
    tls:
      - hosts:
          - argocd.laurencechau.com
        secretName: argocd-secret
  service:
    annotations:
      external-dns.alpha.kubernetes.io/hostname: argocd.laurencechau.com
