apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    k8s-app: kube-router
    tier: node
  name: kube-router
  namespace: kube-system
spec:
  template:
    spec:
      containers:
        - name: kube-router
          args:
            - "--run-router=true"
            - "--run-firewall=false"
            - "--run-service-proxy=false"
            - "--enable-cni=false"
            - "--enable-pod-egress=false"
            - "--enable-ibgp=true"
            - "--enable-overlay=true"
            - "--advertise-cluster-ip=true"
            - "--advertise-external-ip=true"
            - "--advertise-loadbalancer-ip=true"
