apiVersion: v1
kind: Secret
metadata:
  name: argocd-deploy-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/LaurenceChau/argocd-deploy
  name: argocd-deploy
  type: git
